### ISSUE TITLE
Somever.match() does not parse prereleases correctly

### ISSUE THREAD

**Issue by danielleadams** [hapijs/somever#18]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): yes

#### Context

* *node version*: `v16.4.0-pre`
* *module version with issue*: `hapi v20.1.4`
* *last module version without issue*: Not sure
* *environment* (e.g. node, browser, native): Node
* *used with* (e.g. hapi application, another framework, standalone, ...): Node.js Platform Test Suite
* *any other relevant information*: N/A

#### What are you trying to achieve or the steps to reproduce?

When the Node.js release team tests prereleases for Node.js releases, we run the hapi test suite (configured here: https://github.com/nodejs/citgm/blob/main/lib/lookup.json#L2-L5) as part of tests on the Node.js ecosystem. One of the tests fails consistently due to what looks like a bug with how `Somever.match()` parses the format of the version.

In this test: https://github.com/hapijs/hapi/blob/master/test/server.js#L2793-L2805, the test will fail on prereleases with the format of something like `v16.4.0-pre`. `process.version` will always return `vx.y.z`, and the tests do a lot of testing for prerelease syntax, so this looks like a bug.

#### What was the result you got?

```
Failed tests:
   753) Server register() validates node version:
       Expected [Promise] to not reject with an error but got [Error: Plugin test requires node version >=8.x.x but found v16.4.0-pre]
```

#### What result did you expect?

I expected `.match()` to recognize that `v16.4.0-pre` is within the range of `>=8.x.x`.

**Comment by devinivy** [comment]
Hey @danielleadams, thanks for the report.  I believe that somever follows conventions here, but at the same time I see the practical concern.  We worked hard to get hapi into citgm this year, and I'd definitely like to alleviate any logistical issues between hapi and citgm!

Here is why I think somever is in line.  [This script](https://runkit.com/60c18db503676e001ce17d66/60d15aab2e2ad6001a1fce57) demonstrates somever and the semver package agreeing re: `16.4.0-pre` against `>=8.x.x`, and the semver readme has some documentation on how to handle prereleases [here](https://github.com/npm/node-semver#prerelease-tags).

If you can confirm that `process.version` will always take the form `vx.y.z-pre` for node pre-releases then one option may be for us to make the hapi test suite aware of that fact and normalize `process.version` during those course of the relevant tests.

**Comment by kanongil** [comment]
Interesting. I agree that this seems like a hapi issue.

**Comment by danielleadams** [comment]
I can confirm that `process.version` will always return `vx.y.z-pre`. Instead of making the tests aware of that format, would it be easier to use `process.versions.node` instead? That will return the `x.y.z-ext` format that the test expects (without the initial `v`)?

**Comment by devinivy** [comment]
Unfortunately the issue as I understand it is not the presence of the `v` prefix, but rather that `v16.4.0-pre` is not considered to be in the range of `>=8.x.x` per semver conventions around prereleases (docs on that [here](https://github.com/npm/node-semver#prerelease-tags)).  We want to be compatible with citgm, though, so that sort of sends me to two options:
 - Add a `includePrerelease` option to somever similar to the option in semver: https://github.com/npm/node-semver#functions.  Then use that option within hapi for node version matching, or expose it to the user.
 - Update hapi's tests to ignore the prerelease tag by temporarily patching `process.version`, possibly just when it is run under citgm.

Anyone have opinions on which would be better?

**Comment by kanongil** [comment]
I'm in favour of the includePrerelease option, and setting this to true when called from Hapi. I expect this will match people's expectations and the intent of the version check.

**Comment by Nargonath** [comment]
I agree with @kanongil here. I prefer the `includePrerelease` option too.
